### ISSUE TITLE
Cannot import name 'NginxParser' - Windows 7

### ISSUE THREAD

**Issue by IronicMeme** [simon987/opendirectories-bot#4]
Hi there,

I'm trying to manually run the script on Windows 7 with python, however I get the following error:

`E:\opendirectories-bot-master\opendirectories-bot-master>manual.py mkreport "https://computerarchive.org/files/computer/magazines/" "000002"
Traceback (most recent call last):
  File "E:\opendirectories-bot-master\opendirectories-bot-master\manual.py", line 2, in <module>
    from crawler import Crawler
  File "E:\opendirectories-bot-master\opendirectories-bot-master\crawler.py", line 2, in <module>
    from parser import NginxParser, ApacheParser
ImportError: cannot import name 'NginxParser'
`

Any suggestions?
Thanks

**Comment by simon987** [comment]
Can you tell me what version of python you are using?    
try `python -V`

**Comment by IronicMeme** [comment]
3.6.5

**Comment by simon987** [comment]
Should be fixed, can you confirm?

**Comment by IronicMeme** [comment]
Just tried it out, working perfectly now. Thanks!
