### ISSUE TITLE
Export result to txt?

### ISSUE THREAD

**Issue by IronicMeme** [simon987/opendirectories-bot#5]
Hey again,
Just wondering how'd I'd go about exporting the results from a manual report from manual.py to a text file or the like?

I feel like the 6 digit code has something to do with it but I can't find any files that are created at the end of the report. Thanks

**Comment by simon987** [comment]
Should be exported under /static/reports/{6-digit code}.json

**Comment by IronicMeme** [comment]
Ah thats it. Thanks
